name: Hello World Workflow

# This workflow is manually triggered
on:
  workflow_dispatch:

jobs:
  hello-world-job:
    runs-on: ubuntu-latest
    
    steps:
      - name: List GitHub Projects
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh project list --owner hannesrudolph --format json