name: Hello World Workflow

# This workflow is manually triggered
on:
  workflow_dispatch:

jobs:
  hello-world-job:
    runs-on: ubuntu-latest
    
    steps:
      - name: Print Hello World
        run: echo "::debug::Hello World!"
      
      - name: Another way to show debug message
        uses: actions/github-script@v6
        with:
          script: |
            core.debug('Hello World from GitHub Script!')