name: Auto Comment on "Needs Information"

on:
  issues:
    types:
      - labeled

jobs:
  comment_on_issue:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'bug' && github.event.sender.login == 'hannesrudolph'
    steps:
      - name: Check and Comment
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issue_number = context.payload.issue.number;
            const repo = context.repo.repo;
            const owner = context.repo.owner;
            const issue_author = context.payload.issue.user.login;
            const bot_name = "github-actions[bot]"; // Bot username for filtering

            const message = `@${issue_author} Thanks for the report! Would you be able to provide clear steps to reproduce the issue and expected vs. actual behaviour?`;

            // Fetch existing comments
            const { data: comments } = await github.rest.issues.listComments({
              owner,
              repo,
              issue_number
            });

            // Check if the bot has already posted the exact message
            const alreadyCommented = comments.some(comment => 
              comment.user.login === bot_name && comment.body.trim() === message.trim()
            );

            if (!alreadyCommented) {
              await github.rest.issues.createComment({
                owner,
                repo,
                issue_number,
                body: message
              });
            }
