name: Manage Issue Labels

on:
  # Trigger when an issue is labeled
  issues:
    types: [labeled]
  # Manual trigger for testing
  workflow_dispatch:
    inputs:
      issue_number:
        description: 'Issue number to process (leave empty to process all issues)'
        required: false
        type: string

permissions:
  issues: write
  contents: read

jobs:
  manage-labels-for-zenhub:
    runs-on: ubuntu-latest
    steps:
      - name: Process issue when "in-progress" label is added
        if: github.event_name == 'issues' && github.event.action == 'labeled' && github.event.label.name == 'in-progress'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            console.log("Issue labeled with 'in-progress', processing labels...");
            
            const issue = context.payload.issue;
            const issueNumber = issue.number;
            
            console.log(`Processing issue #${issueNumber}: ${issue.title}`);
            console.log(`Current labels: ${issue.labels.map(l => l.name).join(', ') || 'None'}`);
            
            // Filter to keep only "bug" label if present
            const keepLabels = issue.labels
              .map(label => label.name)
              .filter(label => label === "bug" || label === "in-progress");
            
            // Add "documentation" label if not already present
            if (!keepLabels.includes("documentation")) {
              keepLabels.push("documentation");
            }
            
            console.log(`Updating labels to: ${keepLabels.join(', ')}`);
            
            // Update issue with the new set of labels
            await github.rest.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber,
              labels: keepLabels
            });
            
            console.log(`Successfully updated labels for issue #${issueNumber}`);

      - name: Process specific issue (from workflow_dispatch)
        if: github.event_name == 'workflow_dispatch' && inputs.issue_number != ''
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueNumber = parseInt(process.env.ISSUE_NUMBER);
            console.log(`Processing issue #${issueNumber} from manual trigger`);
            
            // Get issue details
            const { data: issue } = await github.rest.issues.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber
            });
            
            // Check if issue has the "in-progress" label
            const labels = issue.labels.map(label => 
              typeof label === 'object' ? label.name : label
            );
            
            const hasInProgressLabel = labels.includes('in-progress');
            console.log(`Issue #${issueNumber} has in-progress label: ${hasInProgressLabel}`);
            
            if (!hasInProgressLabel) {
              console.log(`Issue #${issueNumber} doesn't have the 'in-progress' label. No action taken.`);
              return;
            }
            
            // Filter to keep only "bug" label if present
            const keepLabels = labels.filter(label => 
              label === "bug" || label === "in-progress"
            );
            
            // Add "documentation" label if not already present
            if (!keepLabels.includes("documentation")) {
              keepLabels.push("documentation");
            }
            
            console.log(`Updating labels to: ${keepLabels.join(', ')}`);
            
            // Update issue with the new set of labels
            await github.rest.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber,
              labels: keepLabels
            });
            
            console.log(`Successfully updated labels for issue #${issueNumber}`);
        env:
          ISSUE_NUMBER: ${{ inputs.issue_number }}

      - name: Setup for ZenHub integration
        if: github.event_name == 'workflow_dispatch' && inputs.issue_number == ''
        run: |
          echo "## ZenHub Integration Instructions"
          echo ""
          echo "Based on the debug output, we can see that GitHub Actions cannot directly access ZenHub data."
          echo ""
          echo "To make this workflow work with ZenHub, please follow these steps:"
          echo ""
          echo "1. Create a new label called 'in-progress' in your repository:"
          echo "   - Go to your repository → Issues → Labels"
          echo "   - Click 'New label'"
          echo "   - Name it 'in-progress'"
          echo ""
          echo "2. Set up a process to add the 'in-progress' label when an issue moves to 'In Progress' in ZenHub:"
          echo "   - You can do this manually when you move items in ZenHub"
          echo "   - For automation, consider using ZenHub's webhooks or API if available"
          echo ""
          echo "3. Once an issue has the 'in-progress' label:"
          echo "   - This workflow will automatically:"
          echo "     - Keep only the 'bug' label (if present)"
          echo "     - Add the 'documentation' label"
          echo "     - Keep the 'in-progress' label"
          echo ""
          echo "4. To test the workflow with a specific issue:"
          echo "   - Add the 'in-progress' label to an issue"
          echo "   - Or run this workflow manually with the issue number"