name: Update Issue Labels from Project Board

# This workflow runs on a schedule to sync issue labels with project board columns
# Since GitHub Actions doesn't have a direct event for Projects V2 item movements,
# we'll use a scheduled approach
on:
  # Run every hour
  schedule:
    - cron: '0 * * * *'
  # Also allow manual triggering for testing
  workflow_dispatch:
permissions:
  issues: write    # Needed to modify issue labels
  contents: read   # Needed to access repository
  repository-projects: read  # Needed to access project data
  id-token: write  # Needed for stronger GitHub token

jobs:
  update-labels:
    name: Update Labels Based on Column
    runs-on: ubuntu-latest
    
    steps:
      - name: Sync issue labels with project board columns
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            console.log('Starting project board to issue labels sync');
            
            // Define which projects to process (empty array means process all projects)
            // Configured to only process the "Test Project"
            const targetProjects = [
              "Test Project"  // Only this specific project will be processed
            ];
            
            // Define mapping from column values to labels
            // Only mapping two columns as specified for the test
            // Note: Column names must match exactly what's in the GitHub Project (case-sensitive)
            const columnToLabelMap = {
              'In progress': 'bug',           // GitHub uses "In progress" (lowercase 'p')
              'Done': 'help wanted'          // Maps to 'help wanted' label
            };
            
            try {
              // Get organization/user projects
              const ownerLogin = context.repo.owner;
              
              console.log(`Fetching projects for ${ownerLogin}`);
              
              console.log(`Repository owner: ${ownerLogin}`);
              console.log(`Repository name: ${context.repo.repo}`);
              
              // First, check if we're in an organization
              console.log('Checking for organization projects...');
              
              // This will find projects at the organization level
              const orgProjectsQuery = `
                query($organization: String!) {
                  organization(login: $organization) {
                    projectsV2(first: 10) {
                      nodes {
                        id
                        title
                        number
                        fields(first: 20) {
                          nodes {
                            ... on ProjectV2SingleSelectField {
                              id
                              name
                              options {
                                id
                                name
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              `;
              
              let orgProjects = [];
              try {
                const orgProjectsResult = await github.graphql(orgProjectsQuery, {
                  organization: ownerLogin
                });
                
                orgProjects = orgProjectsResult.organization?.projectsV2?.nodes || [];
                
                console.log("Organization projects found:");
                if (orgProjects.length === 0) {
                  console.log("No organization projects found");
                } else {
                  for (const p of orgProjects) {
                    console.log(`- Org Project: "${p.title}" (#${p.number})`);
                  }
                }
              } catch (error) {
                console.log("Error querying organization projects (likely not an organization):");
                console.log(error.message);
              }
              
              // Now check repository projects
              console.log('Checking for repository projects...');
              
              // Query for repository projects
              const repoProjectsQuery = `
                query($owner: String!, $repo: String!) {
                  repository(owner: $owner, name: $repo) {
                    projectsV2(first: 10) {
                      nodes {
                        id
                        title
                        number
                        fields(first: 20) {
                          nodes {
                            ... on ProjectV2SingleSelectField {
                              id
                              name
                              options {
                                id
                                name
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              `;
              
              const repoProjectsResult = await github.graphql(repoProjectsQuery, {
                owner: context.repo.owner,
                repo: context.repo.repo
              });
              
              // Get all projects from repository
              const repoProjects = repoProjectsResult.repository?.projectsV2?.nodes || [];
              
              // Debug info - list all repository projects found
              console.log("All repository projects found:");
              if (repoProjects.length === 0) {
                console.log("No projects found for this repository");
              } else {
                for (const p of repoProjects) {
                  console.log(`- Project: "${p.title}" (#${p.number})`);
                }
              }
              
              // Also check for user projects
              console.log('Checking for user projects...');
              
              const userProjectsQuery = `
                query($login: String!) {
                  user(login: $login) {
                    projectsV2(first: 10) {
                      nodes {
                        id
                        title
                        number
                        fields(first: 20) {
                          nodes {
                            ... on ProjectV2SingleSelectField {
                              id
                              name
                              options {
                                id
                                name
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              `;
              
              let userProjects = [];
              try {
                const userProjectsResult = await github.graphql(userProjectsQuery, {
                  login: ownerLogin
                });
                
                userProjects = userProjectsResult.user?.projectsV2?.nodes || [];
                
                console.log("User projects found:");
                if (userProjects.length === 0) {
                  console.log("No user projects found");
                } else {
                  for (const p of userProjects) {
                    console.log(`- User Project: "${p.title}" (#${p.number})`);
                  }
                }
              } catch (error) {
                console.log("Error querying user projects:");
                console.log(error.message);
              }
              
              // Process all projects from all sources
              const allProjects = [...orgProjects, ...repoProjects, ...userProjects];
              
              console.log(`Total projects found: ${allProjects.length}`);
              
              // Process each project
              for (const project of allProjects) {
                console.log(`Found project: ${project.title} (#${project.number})`);
                
                // Skip projects not in the target list (if targets are specified)
                if (targetProjects.length > 0 && !targetProjects.includes(project.title)) {
                  console.log(`Skipping project: ${project.title} (not in target list)`);
                  continue;
                }
                
                console.log(`Processing project: ${project.title} (#${project.number})`);
                
                // Find the status field
                const statusField = project.fields.nodes.find(field =>
                  field.name.toLowerCase().includes('status') ||
                  field.name.toLowerCase() === 'state' ||
                  field.name.toLowerCase() === 'column'
                );
                
                // Debug info - print all fields in this project
                console.log(`Fields in project "${project.title}":`);
                for (const field of project.fields.nodes) {
                  console.log(`- Field: "${field.name}" (type: ${field.__typename})`);
                  if (field.options) {
                    console.log(`  Options: ${field.options.map(opt => `"${opt.name}"`).join(', ')}`);
                  }
                }
                
                if (!statusField) {
                  console.log(`No status field found for project ${project.title}`);
                  continue;
                }
                
                console.log(`Using field "${statusField.name}" as status field`);
                
                // Get items in this project
                const itemsQuery = `
                  query($projectId: ID!) {
                    node(id: $projectId) {
                      ... on ProjectV2 {
                        items(first: 100) {
                          nodes {
                            id
                            content {
                              ... on Issue {
                                id
                                number
                                repository {
                                  name
                                  owner {
                                    login
                                  }
                                }
                              }
                            }
                            fieldValues(first: 20) {
                              nodes {
                                ... on ProjectV2ItemFieldSingleSelectValue {
                                  name
                                  field {
                                    ... on ProjectV2SingleSelectField {
                                      name
                                      id
                                    }
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                `;
                
                const itemsResult = await github.graphql(itemsQuery, {
                  projectId: project.id
                });
                
                if (!itemsResult.node.items || !itemsResult.node.items.nodes) {
                  console.log(`No items found in project ${project.title}`);
                  continue;
                }
                
                const items = itemsResult.node.items.nodes;
                console.log(`Found ${items.length} items in project`);
                
                // Process each item
                for (const item of items) {
                  // Skip items that aren't issues
                  if (!item.content || item.content.__typename !== 'Issue') {
                    console.log('Skipping non-issue item');
                    continue;
                  }
                  
                  const issue = item.content;
                  const issueNumber = issue.number;
                  const repoName = issue.repository.name;
                  const repoOwner = issue.repository.owner.login;
                  
                  console.log(`Processing issue #${issueNumber} in ${repoOwner}/${repoName}`);
                  
                  // Find the status field value for this item
                  const statusFieldValue = item.fieldValues.nodes.find(value =>
                    value.field && value.field.id === statusField.id
                  );
                  
                  if (!statusFieldValue) {
                    console.log(`No status value found for issue #${issueNumber}`);
                    continue;
                  }
                  
                  const columnValue = statusFieldValue.name;
                  console.log(`Column value: ${columnValue}`);
                  
                  // Get the label for this column
                  const newColumnLabel = columnToLabelMap[columnValue];
                  if (!newColumnLabel) {
                    console.log(`No label mapping defined for column value: ${columnValue}`);
                    continue;
                  }
                  
                  console.log(`Mapped to label: ${newColumnLabel}`);
                  
                  // Get current issue labels to preserve other labels
                  const { data: issueData } = await github.rest.issues.get({
                    owner: repoOwner,
                    repo: repoName,
                    issue_number: issueNumber
                  });
                  
                  // Define the column-related labels we want to manage
                  const managedLabels = Object.values(columnToLabelMap);
                  
                  // Filter out column-related labels we're managing
                  const otherLabels = issueData.labels
                    .filter(label => !managedLabels.includes(label.name))
                    .map(label => label.name);
                  
                  // Add the new column-related label
                  const newLabels = [...otherLabels, newColumnLabel];
                  
                  // Update the issue with the new labels
                  await github.rest.issues.update({
                    owner: repoOwner,
                    repo: repoName,
                    issue_number: issueNumber,
                    labels: newLabels
                  });
                  
                  console.log(`Updated issue #${issueNumber} with labels: ${newLabels.join(', ')}`);
                }
              }
              
              console.log('Completed project board to issue labels sync');
              
            } catch (error) {
              console.error('Error syncing labels:');
              console.error(error);
            }